name: 'Cache Nix store'
description: 'Restore and save Nix store using GitHub Actions cache to speed up workflows.'
author: 'GitHub'
inputs:
  key:
    description: 'The primary key for restoring and saving a cache.'
    required: true
  
  paths:
    description: |
      - When a newline-separated non-empty list of non-empty path regex expressions, appends them to [`/nix`, `~/.cache/nix`, `~root/.cache/nix`] and uses the resulting list for restoring and saving caches.
      - Otherwise, uses [`/nix`, `~/.cache/nix`, `~root/.cache/nix`] for restoring and saving caches.
    default: ''
  paths-macos:
    description: |
      - Overrides `paths`.
      - Can have effect only on a `macOS` runner.
      - When a newline-separated non-empty list of non-empty path regex expressions, appends them to [`/nix`, `~/.cache/nix`, `~root/.cache/nix`] and uses the resulting list for restoring and saving caches.
      - Otherwise, uses [`/nix`, `~/.cache/nix`, `~root/.cache/nix`] for restoring and saving caches.
    default: ''
  paths-linux:
    description: |
      - Overrides `paths`.
      - Can have effect only on a `Linux` runner.
      - When a newline-separated non-empty list of non-empty path regex expressions, appends them to [`/nix`, `~/.cache/nix`, `~root/.cache/nix`] and uses the resulting list for restoring and saving caches.
      - Otherwise, uses [`/nix`, `~/.cache/nix`, `~root/.cache/nix`] for restoring and saving caches.
    default: ''

  restore-first-match-keys:
    description: |
      - When a newline-separated non-empty list of non-empty key prefixes, if no cache hit occurred for the primary `key`, searches for the first prefix for which there exists a cache with a matching key and restores that cache.
          - The output `cache-hit` returns `false` in this case.
          - Use `restore-first-match-hit` to change this behavior.
      - Otherwise, has no effect.
    default: ''
  restore-first-match-hit:
    description: |
      - Can have effect only if `restore-first-match-keys` has effect.
      - When `true`, if a cache was restored via `restore-first-match-keys`, the output `cache-hit` returns `true`.
      - Otherwise, the output `cache-hit` returns `false`.
    default: 'false'

  restore-all-matches-keys:
    description: |
      - When a newline-separated non-empty list of non-empty key prefixes, tries to restore all caches whose keys match these prefixes.
      - Otherwise, has no effect.
    default: ''

  gc-max-store-size:
    description: |
      - When a number, collects garbage until Nix store size (in bytes) is at most this number just before trying to save a new cache.
      - Otherwise, has no effect.
    default: ''
  gc-max-store-size-macos:
    description: |
      - Overrides 'gc-max-store-size'.
      - Can have effect only on a `macOS` runner.
      - When a number, collects garbage until Nix store size (in bytes) is at most this number just before trying to save a new cache.
      - Otherwise, has no effect.
    default: ''
  gc-max-store-size-linux:
    description: |
      - Overrides 'gc-max-store-size'.
      - Can have effect only on a `Linux` runner.
      - When a number, collects garbage until Nix store size (in bytes) is at most this number just before trying to save a new cache.
      - Otherwise, has no effect.
    default: ''
  
  purge:
    description: |
      - When `true`, purges (possibly zero) old caches.
      - Otherwise, has no effect.
    default: 'false'
  purge-overwrite:
    description: |
      - Can have effect only if `purge: true`.
      - When `always`, always purges old cache(s) with the primary `key` before saving a new cache with the primary `key`.
      - When `never`, never purges old cache(s) with the primary `key` and never saves a new cache with the primary `key`.
      - Otherwise, purges old caches using purging criteria before saving a new cache with the primary `key`.
    default: ''
  purge-keys:
    description: |
      - Can have effect only if `purge: true`.
      - When a newline-separated non-empty list of non-empty cache key prefixes, collects for purging all cache keys that match these prefixes.
      - Otherwise, has no effect.
    default: ''
  purge-accessed-max-age:
    description: |
      - Can have effect only if `purge-keys` has effect.
      - When a number, purges caches last accessed more than this number of seconds ago relative to the start of the cache saving phase.
      - Otherwise, has no effect on purging.
    default: ''
  purge-created-max-age:
    description: |
      - Can have effect only if `purge-keys` has effect.
      - When a number, purges caches created more than this number of seconds ago relative to the start of the Save phase.
      - Otherwise, has no effect on purging.
    default: ''
  
  upload-chunk-size:
    description: 'When a number, uses it as the chunk size (in bytes) to split up large files during upload.'
    # The original default value may be provided here (https://github.com/actions/cache/issues/1292)
    # 32MB
    default: '33554432'

  fail-on-cache-miss:
    description: |
      - When `true`, fails if a cache entry is found neither via the primary `key` nor via the `restore-first-match-keys`.
      - Otherwise, has no effect.
    default: 'false'

  lookup-only-on-key-hit:
    description: |
      - When `true`, if a cache with the `key` exists, skips Restore and Save phases.
        The output `cache-hit` returns `true`.
        The outputs `cache-primary-key`, `cache-restored-key` return the primary `key`.
      - Otherwise, runs Restore and Save phases.
    default: 'false'

  token:
    description: 'Used to communicate with GitHub API.'
    default: ${{ github.token }}
outputs:
  cache-hit:
    description: 'A boolean value. Indicates whether a cache was restored successfully, either via the primary `key` or via the `restore-first-match-keys` if `restore-first-match-hit` was set.'
  cache-primary-key:
    description: 'A string. The primary `key`.'
  cache-restored-key:
    description: 'A string. The key of a restored cache.'
  caches-restored-keys:
    description: 'An array of strings (JSON). Keys of restored caches.'
runs:
  using: 'node16'
  main: 'dist/restore/index.js'
  post: 'dist/save/index.js'
  post-if: success()
branding:
  icon: 'archive'
  color: 'gray-dark'
