name: 'Cache Nix store'
description: 'Restore and save Nix store using GitHub Actions cache to speed up workflows.'
author: 'GitHub'
inputs:
  key:
    description: 'The primary key for restoring and saving the cache.'
    required: true
  
  restore-keys-first:
    description: "When a newline-separated non-empty list of non-empty key prefixes and no cache hit occurred for the primary `key`, searches for the first prefix for which there exists a cache with a matching key and restores that cache. The output `cache-hit` returns `false` in this case. Use `restore-keys-first-hit` to change this behavior."
    default: ''
  restore-keys-first-hit:
    description: 'When `true` and a cache was restored via `restore-keys-first`, the output `cache-hit` returns `true`. Otherwise, the output `cache-hit` returns `false`.'
    default: 'false'
  
  restore-keys-all:
    description: 'When a newline-separated non-empty list of non-empty key prefixes, tries to restore all caches whose keys match these prefixes.'
    default: ''

  max-store-size-macos:
    description: 'When a number (of bytes) and on a `macOS` runner, collects garbage until Nix store size (in bytes) is at most this number just before trying to save a new cache. When the input is not a number, does not collect garbage.'
    default: ''
  max-store-size-linux:
    description: 'When a number (of bytes) and on a `Linux` runner, collects garbage until Nix store size (in bytes) is at most this number just before trying to save a new cache. When the input is not a number, does not collect garbage.'
    default: ''
  
  purge:
    description: 'When `true`, purges old caches. Otherwise, does not purge them.'
    default: 'false'
  purge-overwrite:
    description: "When `always`, always purges old caches with the primary `key` before saving a new cache with the primary `key`. When `never`, never purges an old cache with the primary `key` and never saves a new cache with the primary `key`. Otherwise, saves a new cache with the primary `key` if after purging there is no old cache with the primary `key`."
    default: ''
  purge-keys:
    description: 'When a newline-separated non-empty list of non-empty cache key prefixes, collects cache keys that match these prefixes.'
    default: ''
  purge-accessed-max-age:
    description: 'When a number, purges caches last accessed more than this number of seconds ago relative to the start of the cache saving phase. When not a number, this criterion is ignored.'
    default: ''
  purge-created-max-age:
    description: 'When a number, purges caches created more than this number of seconds ago relative to the start of the cache saving phase. When not a number, this criterion is ignored.'
    default: ''
  
  upload-chunk-size:
    description: 'The chunk size used to split up large files during upload, in bytes.'
    # The original default value may be provided here (https://github.com/actions/cache/issues/1292)
    # 32MB
    default: '33554432'
  fail-on-cache-miss:
    description: 'Fail the workflow if a cache entry is found neither via the primary `key`, nor via the `restore-keys-first`.'
    default: 'false'
  token:
    description: 'Used to communicate with GitHub API.'
    default: ${{ github.token }}
outputs:
  cache-hit:
    description: 'A boolean value that indicates whether a cache was restored successfully, either via the primary `key` or via the `restore-keys-first` if `restore-keys-first-hit` is set.'
  cache-primary-key:
    description: 'The resolved primary `key`.'
  cache-matched-key:
    description: 'Key of the cache that was restored.'
runs:
  using: 'node16'
  main: 'dist/restore/index.js'
  post: 'dist/save/index.js'
  post-if: success()
branding:
  icon: 'archive'
  color: 'gray-dark'
