name: 'Restore Nix store'
description: 'Restore Nix store using GitHub Actions cache to speed up workflows.'
author: 'GitHub'
inputs:
  key:
    description: 'The primary key for restoring a cache.'
    required: true
  
  restore-first-match-keys:
    description: |
      - When a newline-separated non-empty list of non-empty key prefixes, if no cache hit occurred for the primary `key`, searches for the first prefix for which there exists a cache with a matching key and restores that cache.
          - The output `cache-hit` returns `false` in this case.
          - Use `restore-first-match-hit` to change this behavior.
      - Otherwise, has no effect.
    default: ''
  restore-first-match-hit:
    description: |
      - When `true`, if a cache was restored via `restore-first-match-keys`, the output `cache-hit` returns `true`.
      - Otherwise, the output `cache-hit` returns `false`.
    default: 'false'

  restore-all-matches-keys:
    description: |
      - When a newline-separated non-empty list of non-empty key prefixes, tries to restore all caches whose keys match these prefixes.
      - Otherwise, has no effect.
    default: ''

  fail-on-cache-miss:
    description: |
      - When `true`, fail the workflow if a cache entry is found neither via the primary `key` nor via the `restore-first-match-keys`.
      - Otherwise, has no effect on the action.
    default: 'false'

outputs:
  cache-hit:
    description: 'A boolean value that indicates whether a cache was restored successfully, either via the primary `key` or via the `restore-first-match-keys` if `restore-first-match-hit` was set.'
  cache-primary-key:
    description: 'The resolved primary `key`.'
  cache-matched-key:
    description: 'Key of the restored cache.'
  caches-matched-keys:
    description: 'Keys of restored caches.'
runs:
  using: 'node16'
  main: '../dist/restore-only/index.js'
branding:
  icon: 'archive'
  color: 'gray-dark'
