name: "Restore Nix store"
description: "Restore Nix store using GitHub Actions cache to speed up workflows."
author: "GitHub"
inputs:
  primary-key:
    description: |
      - When a non-empty string, the action uses this key for restoring a cache.
      - Otherwise, the action fails.
    required: true
  
  restore-prefixes-first-match:
    description: |
      - When a newline-separated non-empty list of non-empty key prefixes, when there's a miss on the `primary-key`, 
        the action searches in this list for the first prefix for which there exists a cache 
        with a matching key and the action tries to restore that cache.
      - Otherwise, this input has no effect.
    default: ""
  restore-prefixes-all-matches:
    description: |
      - When a newline-separated non-empty list of non-empty key prefixes, the action tries to restore 
        all caches whose keys match these prefixes.
      - Otherwise, this input has no effect.
    default: ""

  skip-restore-on-hit-primary-key:
    description: |
      - Can have an effect only when `restore-prefixes-first-match` has no effect.
      - When `true`, when there's a hit on the `primary-key`, the action doesn't restore caches.
      - Otherwise, this input has no effect.
    default: "false"

  fail-on:
    description: |
      - Input form: `<key type>.<result>`.
      - `<key type>` options: `primary-key`, `first-match`.
      - `<result>` options: `miss`, `not-restored`.
      - When the input satisfies the input form, when the event described in the input happens, the action fails.
        - Example:
          - Input: `primary-key.not-restored`.
          - Event: a cache could not be restored via the `primary-key`.
      - Otherwise, this input has no effect.
    default: ""

  nix:
    description: |
      - When `true`, the action can do Nix-specific things.
      - Otherwise, the action doesn't do them.
    default: "true"

  save:
    description: |
      - When `true`, the action can save a cache with the `primary-key`.
      - Otherwise, the action can't save a cache.
    default: "true"

  paths:
    description: |
      - When `nix: true`, uses `["/nix", "~/.cache/nix", "~root/.cache/nix"]` as default paths. Otherwise, uses an empty list as default paths.
      - When a newline-separated non-empty list of non-empty path patterns (see [`@actions/glob`](https://github.com/actions/toolkit/tree/main/packages/glob) for supported patterns), the action appends it to default paths and uses the resulting list for restoring caches.
      - Otherwise, the action uses default paths for restoring caches.
    default: ""
  paths-macos:
    description: |
      - Overrides `paths`.
      - Can have an effect only when on a `macOS` runner.
      - When `nix: true`, uses `["/nix", "~/.cache/nix", "~root/.cache/nix"]` as default paths. Otherwise, uses an empty list as default paths.
      - When a newline-separated non-empty list of non-empty path patterns (see [`@actions/glob`](https://github.com/actions/toolkit/tree/main/packages/glob) for supported patterns), the action appends it to default paths and uses the resulting list for restoring caches.
      - Otherwise, the action uses default paths for restoring caches.
    default: ""
  paths-linux:
    description: |
      - Overrides `paths`.
      - Can have an effect only when on a `Linux` runner.
      - When `nix: true`, uses `["/nix", "~/.cache/nix", "~root/.cache/nix"]` as default paths. Otherwise, uses an empty list as default paths.
      - When a newline-separated non-empty list of non-empty path patterns (see [`@actions/glob`](https://github.com/actions/toolkit/tree/main/packages/glob) for supported patterns), the action appends it to default paths and uses the resulting list for restoring caches.
      - Otherwise, the action uses default paths for restoring caches.
    default: ""

  

  token:
    description: The action uses it to communicate with GitHub API.
    default: ${{ github.token }}
outputs:
  primary-key:
    description: |
      - A string.
      - The `primary-key`.

  hit:
    description: |
      - A boolean value.
      - `true` when `hit-primary-key` is `true` or `hit-first-match` is `true`.
      - `false` otherwise.
  hit-primary-key:
    description: |
      - A boolean value.
      - `true` when there was a hit on the `primary-key`.
      - `false` otherwise.
  hit-first-match:
    description: |
      - A boolean value.
      - `true` when there was a hit on a key matching `restore-prefixes-first-match`.
      - `false` otherwise.

  restored-key:
    description: |
      - A string.
      - The key of a cache restored via the `primary-key` or via the `restore-prefixes-first-match`.
      - An empty string otherwise.

  restored-keys:
    description: |
      - A possibly empty array of strings (JSON).
      - Keys of restored caches.
      - Example: `["key1", "key2"]`.
runs:
  using: "node16"
  main: "../dist/restore-only/index.js"
  
branding:
  icon: "archive"
  color: "gray-dark"
