name: 'Restore Cache'
description: 'Restore Nix store using GitHub Actions cache to speed up workflows.'
author: 'GitHub'
inputs:
  key:
    description: 'An explicit key for restoring the cache'
    required: true
  
  restore-keys-first:
    description: "When a newline-separated non-empty list of non-empty key prefixes and no cache hit occurred for the primary `key`, searches for the first prefix for which there exists a cache with a matching key and restores that cache. The output `cache-hit` returns `false` in this case. Use `restore-keys-first-hit` to change this behavior."
    default: ''
  restore-keys-first-hit:
    description: 'When `true` and a cache was restored via `restore-keys-first`, the output `cache-hit` returns `true`. Otherwise, the output `cache-hit` returns `false`.'
    default: 'false'
  
  restore-keys-all:
    description: 'When a newline-separated non-empty list of non-empty key prefixes, tries to restore all caches whose keys match these prefixes.'
    default: ''

  fail-on-cache-miss:
    description: 'Fail the workflow if a cache entry is found neither via the primary `key`, nor via the `restore-keys-first`.'
    default: 'false'
  
outputs:
  cache-hit:
    description: 'A boolean value that indicates whether a cache was restored successfully, either via the primary `key` or via the `restore-keys-first` if `restore-keys-first-hit` was set.'
  cache-primary-key:
    description: 'The resolved primary `key`.'
  cache-matched-key:
    description: 'Key of the cache that was restored.'
runs:
  using: 'node16'
  main: '../dist/restore-only/index.js'
branding:
  icon: 'archive'
  color: 'gray-dark'
