name: "Save Nix store"
description: "Save Nix store using GitHub Actions cache to speed up workflows."
author: "GitHub"
inputs:
  primary-key:
    description: |
      - When a non-empty string, the action uses this key for saving a cache.
      - Otherwise, the action fails.
    required: true
  
  

  nix:
    description: |
      - When `true`, the action can do Nix-specific things.
      - Otherwise, the action doesn't do them.
    default: "true"

  save:
    description: |
      - When `true`, the action can save a cache with the `primary-key`.
      - Otherwise, the action can't save a cache.
    default: "true"

  paths:
    description: |
      - When `nix: true`, uses `["/nix", "~/.cache/nix", "~root/.cache/nix"]` as default paths. Otherwise, uses an empty list as default paths.
      - When a newline-separated non-empty list of non-empty path patterns (see [`@actions/glob`](https://github.com/actions/toolkit/tree/main/packages/glob) for supported patterns), the action appends it to default paths and uses the resulting list for saving caches.
      - Otherwise, the action uses default paths for saving caches.
    default: ""
  paths-macos:
    description: |
      - Overrides `paths`.
      - Can have an effect only when on a `macOS` runner.
      - When `nix: true`, uses `["/nix", "~/.cache/nix", "~root/.cache/nix"]` as default paths. Otherwise, uses an empty list as default paths.
      - When a newline-separated non-empty list of non-empty path patterns (see [`@actions/glob`](https://github.com/actions/toolkit/tree/main/packages/glob) for supported patterns), the action appends it to default paths and uses the resulting list for saving caches.
      - Otherwise, the action uses default paths for saving caches.
    default: ""
  paths-linux:
    description: |
      - Overrides `paths`.
      - Can have an effect only when on a `Linux` runner.
      - When `nix: true`, uses `["/nix", "~/.cache/nix", "~root/.cache/nix"]` as default paths. Otherwise, uses an empty list as default paths.
      - When a newline-separated non-empty list of non-empty path patterns (see [`@actions/glob`](https://github.com/actions/toolkit/tree/main/packages/glob) for supported patterns), the action appends it to default paths and uses the resulting list for saving caches.
      - Otherwise, the action uses default paths for saving caches.
    default: ""

  gc-max-store-size:
    description: |
      - Can have an effect only when `nix: true`, `save: true`.
      - When a number, the action collects garbage until Nix store size (in bytes) is at most this number just before the action tries to save a new cache.
      - Otherwise, this input has no effect.
    default: ""
  gc-max-store-size-macos:
    description: |
      - Can have an effect only when `nix: true`, `save: true`.
      - Overrides `gc-max-store-size`.
      - Can have an effect only when on a `macOS` runner.
      - When a number, the action collects garbage until Nix store size (in bytes) is at most this number just before the action tries to save a new cache.
      - Otherwise, this input has no effect.
    default: ""
  gc-max-store-size-linux:
    description: |
      - Can have an effect only when `nix: true`, `save: true`.
      - Overrides `gc-max-store-size`.
      - Can have an effect only when on a `Linux` runner.
      - When a number, the action collects garbage until Nix store size (in bytes) is at most this number just before the action tries to save a new cache.
      - Otherwise, this input has no effect.
    default: ""

  purge:
    description: |
      - When `true`, the action purges (possibly zero) caches.
      - Otherwise, this input has no effect.
    default: "false"
  purge-overwrite:
    description: |
      - Can have an effect only when `purge: true`.
      - When `always`, the action always purges cache with the `primary-key`.
      - When `never`, the action never purges cache with the `primary-key`.
      - Otherwise, the action purges old caches using purging criteria.
    default: ""
  purge-prefixes:
    description: |
      - Can have an effect only when `purge: true`.
      - When a newline-separated non-empty list of non-empty cache key prefixes, the action collects all cache keys that match these prefixes.
      - Otherwise, this input has no effect.
    default: ""
  purge-last-accessed:
    description: |
      - Can have an effect only when `purge: true`.
      - When a number, the action selects for purging caches last accessed more than this number of seconds ago relative to the start of the Save phase.
      - Otherwise, this input has no effect.
    default: ""
  purge-created:
    description: |
      - Can have an effect only when `purge: true`.
      - When a number, the action selects for purging caches created more than this number of seconds ago relative to the start of the Save phase.
      - Otherwise, this input has no effect.
    default: ""

  upload-chunk-size:
    # The original default value may be provided here (https://github.com/actions/cache/issues/1292)
    # 32MB
    description: |
      - When a number, the action uses it as the chunk size (in bytes) to split up large files during upload.
      - Otherwise, the action uses the default value `33554432` (32MB).
    default: ""

  token:
    description: The action uses it to communicate with GitHub API.
    default: ${{ github.token }}

runs:
  using: "node16"
  main: "../dist/save-only/index.js"
  
branding:
  icon: "archive"
  color: "gray-dark"
